name: procurement-analytics
channels:
  - conda-forge
  - defaults
  - plotly

dependencies:
  # Core Python
  - python=3.10

  # Core Data Analysis
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  - statsmodels>=0.14.0

  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0

  # Machine Learning
  - scikit-learn>=1.3.0
  - xgboost>=1.7.0
  - lightgbm>=3.3.0

  # Jupyter
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - ipywidgets>=8.0.0

  # Data I/O
  - openpyxl>=3.1.0
  - xlsxwriter>=3.1.0
  - pyarrow>=12.0.0

  # Utilities
  - pyyaml>=6.0.0
  - tqdm>=4.65.0
  - python-dateutil>=2.8.0

  # Testing
  - pytest>=7.4.0
  - pytest-cov>=4.1.0

  # Code Quality
  - black>=23.7.0
  - flake8>=6.0.0

  # Pip dependencies (not available in conda)
  - pip
  - pip:
    - streamlit>=1.25.0
    - dash>=2.12.0
    - great-expectations>=0.17.0
    - prophet>=1.1.4
    - pmdarima>=2.0.0
    - missingno>=0.5.2
    - loguru>=0.7.0